### ISSUE TITLE
Authentication via OIDC is missing

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-js-client#11]
So far, only `authenticateBasic` is available. The `authenticateOIDC` method exists, but the only thing it does is throwing an error: "Not implemented (yet)"

**Comment by m-mohr** [comment]
Potential library to use: https://github.com/IdentityModel/oidc-client-js

**Comment by m-mohr** [comment]
Part of the roadmap in README.md. Remove once the issue is closed.

**Comment by m-mohr** [comment]
Work started in the feature/oidc branch.

**Comment by m-mohr** [comment]
Experimental support is available, will be improved whenever requested/required.
