### ISSUE TITLE
Add example that implements AppAuth JS

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-js-client#32]
For non-web usage we may want to provide an example that implements AppAuth JS, so that (1) we have a better example of how to use setOidcProviderFactory and (2) we have a starting guide for other environments (node, app, ...).

Related: #30

cc @jneijt - have you looked into AppAuth JS and can provide some example code?

**Comment by jneijt** [comment]
@m-mohr Sorry, I missed this somehow.
Unfortunately I haven't had the time to look into AppAuth JS and as the current implementation is "kind-of-working" its priority is not that high anymore on our side for now.

**Comment by m-mohr** [comment]
Obsolete, see #49
