### ISSUE TITLE
Default to Auth code flow (with PKCE) instead of implicit flow

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-js-client#39]
From my initial testing of OIDC auth against our VITO backend, I think the web editor is using the implicit flow, is this correct?

I was wondering why the auth code flow with PKCE isn't used as a lot of online resources advise against the implicit flow and recommend auth code + PKCE instead.
https://oauth.net/2/grant-types/implicit/ is a good starting point more background

**Comment by m-mohr** [comment]
I've tried to response_type to code, which should activate Auth Code w/ PKCE, but it doesn't work for me. It looks like a bug in the oidc library to me, but I'm not 100% sure. Hope https://github.com/IdentityModel/oidc-client-js/issues/1256 helps...

**Comment by m-mohr** [comment]
Waiting for https://github.com/IdentityModel/oidc-client-js/pull/1258 to be merged (or solved differently). It's actually a bug in the OIDC library.

**Comment by m-mohr** [comment]
The author of the OIDC library has closed the bugfix I submitted as PR without any detailed checks so we won't get any AuthCode support in the JS client and will have to stay with Implicit until a new library gets developed. So closing here, too. I can't do anything.

**Comment by m-mohr** [comment]
I got it reconsidered and it's now fixed so that I can now include the flow. It's available since v1.11.3 of the oidc-client-js

**Comment by m-mohr** [comment]
This will be released with 1.0.3, so it supports AuthCode w/PKCE but the default is still Implicit. The default will change to AuthCode in 2.0.0, as it's a breaking change. Still, the Web Editor will implement AuthCode w/PKCE now and use it in the next version already. Implicit is then removed from the Web Editor completely.
