### ISSUE TITLE
parameter naming issues

### ISSUE THREAD

**Issue by jonathom** [Open-EO/openeo-js-client#46]
I noticed some behaviour that I can't quite explain when executing a .js script. See [this gist](https://gist.github.com/jonathom/b1ee02c58302c0b77c5f719f7d13c8cd) with the code I'm referring to.

1. The script in total is failing because in [line 40](https://gist.github.com/jonathom/b1ee02c58302c0b77c5f719f7d13c8cd#file-js_example_gee-js-L40), I named the parameter `,process = scale_` as such. If I only put `, scale_`, not mentioning the name, the script runs without error.
2. Although I'm naming parameters these names don't really seem to matter. E.g. when I switch `reducer = ...` and `dimension = 't'` in [line 32](https://gist.github.com/jonathom/b1ee02c58302c0b77c5f719f7d13c8cd#file-js_example_gee-js-L32), the script fails to execute.

Can't make any sense of it. 
EDIT: using authenticateBasic, deleted login for upload

**Comment by m-mohr** [comment]
JavaScript doesn't have named parameters, you just provide parameters by order.

So for example your code `var cube_s2_b348_red_lin = builder.apply(data = cube_s2_b348_red, process = scale_); // can't name "process"` must be `var cube_s2_b348_red_lin = builder.apply(cube_s2_b348_red, scale_); // can't name "process"` instead.

It seems you are doing too much R and Python. :-D

**Comment by jonathom** [comment]
alright :), I will change this in the cookbook as well.

**Comment by jonathom** [comment]
@m-mohr  One question though: If I can't name parameters, how can I skip a parameter that I don't need to pass. E.g. in `array_element`, where I can choose to pass either an index or a label?
![Screenshot from 2021-05-06 14-40-28](https://user-images.githubusercontent.com/45635480/117299625-0bf7d800-ae79-11eb-9a23-8fb9e61da0dd.png)
(I am aware that there are easier ways to accomplish the overall task here)

**Comment by m-mohr** [comment]
So your code could be shortened to:

var _ndvi = (data, _, child) => child.normalized_difference(data[0], data["B08"]);

**Comment by jonathom** [comment]
great, thanks! VITO backend throws an error cause it expects a number for some reason, but that's their thing.
Anyway, how's this for a bandmath definition? Or is it generally done differently?
![Screenshot from 2021-05-06 14-56-22](https://user-images.githubusercontent.com/45635480/117301760-41052a00-ae7b-11eb-9066-ac8bbc918573.png)

**Comment by jonathom** [comment]
Maybe this is the place for using `Formula`?

**Comment by m-mohr** [comment]
Yes, that's a good place for using "Formula". For everything where you compute on a single number (i.e. not an array of numbers), Formula is probably the best choice.
