### ISSUE TITLE
Second subscription to the same topic overrides listener

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-js-client#5]
The `subscribe` command allows an individual callback for every subscription, i.e. if we've got two subscriptions for the same topic but with different parameters, they can have individual callback functions. So far the listeners are saved per topic, i.e. the second subscription for the same topic overrides the listener of the first subscription to that topic.

**Comment by m-mohr** [comment]
That was somehow a "known limitation" due to me being rushed getting a first draft. Thanks for the PR.
