### ISSUE TITLE
TypeError: con.authenticateOIDC is not a function

### ISSUE THREAD

**Issue by rifatSDAS** [Open-EO/openeo-js-client#58]
Hi, 

I am trying to test openEO JS client for my web app. During testing I got these errors

I am trying the Full Example from 
https://documentation.dataspace.copernicus.eu/APIs/openEO/JavaScript_Client/JavaScript.html

When
```
var con = await OpenEO.connect("https://openeo.dataspace.copernicus.eu");
// Authenticate ourselves via Basic authentication
await con.authenticateOIDC();
```
**ERROR** _TypeError: con.authenticateOIDC is not a function_

And when I am using 
`await con.authenticateBasic("my-CDSE-username", "my-CDSE-password");`

**ERROR** _Error: Credentials are not correct_

N.B. I calling openEO api from HTML script tags
```
<script src="https://cdn.jsdelivr.net/npm/axios@0.21/dist/axios.js"></script>
<script src="https://cdn.jsdelivr.net/npm/oidc-client@1/lib/oidc-client.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@openeo/js-client@2/openeo.js"></script>
```
Any insight will be appreciated :-)

**Comment by m-mohr** [comment]
authenticateOIDC doesn't exist, the docs in the CDSE are wrong. Please contact them to get it fixed.
You need to use `listAuthProviders` and then filter for the OIDC Proivder(s) you want to use.
https://open-eo.github.io/openeo-js-client/latest/Connection.html#listAuthProviders

Something like should give you all OIDC providers configured through the API:
```js
let providers = await con.listAuthProviders();
let oidcProviders = providers.filter(p => p.getType() === "oidc");
```
