### ISSUE TITLE
Use object-hash library instead of JSON.stringify

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-js-client#6]
To turn the parameter objects into strings (for usage as keys in a `Map`), the Earth Engine driver uses the [*object-hash* library](https://www.npmjs.com/package/object-hash). In this client, I used `JSON.stringify` instead because it was at hand and I don't like additional libraries if I don't really need them.

Since @m-mohr had a reason for choosing the lib over the built-in (I remember something like "JSON.stringify is not deterministic"?) it may be smart to use that lib here, too.

**Comment by m-mohr** [comment]
When working on this, we should have a closer look to #7. I added some comments there.

**Comment by m-mohr** [comment]
I tried to come up with a more light-weight approach than the hash-library based on https://en.wikipedia.org/wiki/Jenkins_hash_function - will probably be not 100% safe to collisions, but should be suitable for our use-case.
